### ISSUE TITLE
MPRIS not working in KDE Plasma 5.26.4

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music#349]
In GitLab by @cupricreki on Dec 21, 2022, 10:32

Cannot control sublime text with media keys, and plasmashell does not register media being played. KDE connect works fine.

- Arch Linux
- KDE Plasma 5.26.4
- Sublime Music v0.11.16 installed from aur

```
plasmashell[15351]: kde.dataengine.mpris: "org.mpris.MediaPlayer2.sublimemusic" does not implement org.freedesktop.DBus.Properties correctly Error message was "org.freedesktop.DBus.Error.UnknownMethod" "Object does not exist at path “/org/mpris/MediaPlayer2”"
````

```
plasmashell[15351]: kde.dataengine.mpris: Failed to find working MPRIS2 interface for "org.mpris.MediaPlayer2.sublimemusic"
```

**Comment by sumnerevans** [comment]
Has the MPRIS spec changed or something? I'd like to know what I'm implementing incorrectly.

**Comment by sumnerevans** [comment]
In GitLab by @cupricreki on Dec 21, 2022, 10:36

I don't know exactly what the issue is but I've never gotten media controls to work in KDE Plasma with Sublime Music. Been using it for about a year over many reinstalls.

**Comment by sumnerevans** [comment]
In GitLab by @karmanyaahm on Dec 27, 2022, 19:31

Maybe this is just my machine but when my
1. Computer is started
2. I start sublime music
3. It doesn't work

but,
1. Computer is started
2. Start Sublime Music
3. `systemctl --user restart plasma-plasmashell.service`
4. It works

It also works on the lock screen sometimes.

**Comment by sumnerevans** [comment]
In GitLab by @cupricreki on Dec 27, 2022, 19:53

Just confirmed this works for me as well.

**Comment by numerfolt** [comment]
Same issue here with plasmashell 5.27.6 and sublime-music 1.12.0-2

**Comment by CupricReki** [comment]
This fixes the issue I had in KDE. Thanks so much! Great job! ☺️

**Comment by miawgogo** [comment]
Adding another confirmation that the issue has been fixed and that mpris is behaving as expected, installed from the `-git` package on the AUR 
![image](https://github.com/sublime-music/sublime-music/assets/7449028/bd0d9fcf-149f-422a-b6ee-f28711cb0d14)
