### PR TITLE
Make mpris compatible with kde

### LINKED ISSUE #349: MPRIS not working in KDE Plasma 5.26.4
In GitLab by @cupricreki on Dec 21, 2022, 10:32

Cannot control sublime text with media keys, and plasmashell does not register media being played. KDE connect works fine.

- Arch Linux
- KDE Plasma 5.26.4
- Sublime Music v0.11.16 installed from aur

```
plasmashell[15351]: kde.dataengine.mpris: "org.mpris.MediaPlayer2.sublimemusic" does not implement org.freedesktop.DBus.Properties correctly Error message was "org.freedesktop.DBus.Error.UnknownMethod" "Object does not exist at path “/org/mpris/MediaPlayer2”"
````

```
plasmashell[15351]: kde.dataengine.mpris: Failed to find working MPRIS2 interface for "org.mpris.MediaPlayer2.sublimemusic"
```

### PR DESCRIPTION
**Pull request by metallkopf**
I don't know if the interface is not ready when KDE starts querying it, but making this change to the codebase gets MPRIS registered correctly.

The connection object didn't seem to change when calling the new function, I looked at the differences between bus_own_name_on_connection and bus_own_name, the former calls to has_connection (which already has) and the latter calls to bus_get. I tried some combinations by adding a call to bus_get* but I couldn't get it to work.

This code fixes #349, #41, works on Gnome, and puts to rest my former PR #442.

image

### CODE REVIEW

File: sublime_music/dbus/manager.py [hunk 1]
```diff
@@ -72,23 +72,24 @@ def dbus_name_acquired(connection: Gio.DBusConnection, name: str):
...
-                    self.on_get_property,
-                    self.on_set_property,
-                )
+                    connection.register_object(
+                        "/org/mpris/MediaPlayer2",
+                        node_info.interfaces[0],
+                        self.on_method_call,
+                        self.on_get_property,
+                        self.on_set_property,
+                    )
```
Comment (sumnerevans) [inline sublime_music/dbus/manager.py]: was this change necessary?

**Review by sumnerevans — COMMENTED** [review]
sorry for the delay

File: sublime_music/dbus/manager.py (hunk 1 above)
Comment (metallkopf) [reply sublime_music/dbus/manager.py]: no, but node_info is defined at that level

Comment (sumnerevans) [reply sublime_music/dbus/manager.py]: It's better to keep the `with` statements as short as possible. Only the `f.read()` needs to be within the `with`, so please unindent this. Since it's within the same scope, Python handles this just fine

**Comment by CupricReki** [comment]
@metallkopf Thanks so much for taking the time to fix this! Works great for me so far in KDE.
